import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { GoogleTagManager } from '@next/third-parties/google';
import './globals.css';
import { ModalProvider } from '@/contexts/ModalContext';
import Providers from './provider';
import { ToastProvider } from '@/contexts/ToastContext';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'TEAMFICIAL',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: '48x48', type: 'image/x-icon' },
      { url: '/favicon.svg', type: 'image/svg+xml' },
    ],
    apple: '/apple-touch-icon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} antialiased`}>
        <Providers>
          <ToastProvider>
            <ModalProvider>{children}</ModalProvider>
          </ToastProvider>
        </Providers>
        <GoogleTagManager gtmId="GTM-5KPSS9WV" />
      </body>
    </html>
  );
}
