import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ModalProvider } from '@/contexts/ModalContext';
import Providers from './provider';
import { ToastProvider } from '@/contexts/ToastContext';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'TEAMFICIAL',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} antialiased`}>
        <Providers>
          <ToastProvider>
            <ModalProvider>{children}</ModalProvider>
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
