import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ModalProvider } from '@/contexts/ModalContext';
import Providers from './provider';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} antialiased`}>
        <Providers>
          <ModalProvider>{children}</ModalProvider>
        </Providers>
      </body>
    </html>
  );
}
